name: clan_of_pets
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.8+8

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1
  flutter_spinkit: ^5.2.1
  persistent_bottom_nav_bar: ^5.0.2
  carousel_slider: ^4.2.1
  fl_chart: ^0.67.0
  image_picker: ^1.0.8
  file_picker: ^8.0.0+1
  dropdown_button2: ^2.3.9
  easy_date_timeline:
  csc_picker: ^0.2.7
  language_picker: ^0.4.3
  dotted_border: ^2.1.0
  otp_text_field: ^1.1.3
  uuid: ^4.4.0
  intl: ^0.19.0
  google_maps_flutter: ^2.6.1
  flutter_secure_storage: ^9.0.0
  http: ^1.2.1
  shimmer: ^3.0.0
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  firebase_messaging: ^14.9.1
  timezone: ^0.9.3
  flutter_local_notifications: ^17.1.0
  http_parser: ^4.0.2
  flutter_pdfview: ^1.3.2
  flutter_barcode_scanner: ^2.0.0
  share_plus: ^9.0.0
  web_socket_channel: 
  socket_io_client: 
  url_launcher: ^6.3.0
  chewie: 
  video_player: 
  social_media_recorder: ^1.1.13
  go_router: ^14.1.1
  screenshot:
  path_provider: ^2.1.3
  geocoding: ^3.0.0
  location: ^6.0.2
  geolocator: ^12.0.0
  country_list_pick: ^1.0.1+6
  image_cropper: ^7.0.4
  pdf: ^3.10.8
  pinput: ^5.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/reminder/